project:
  type: website
  output-dir: documents

website:
  title: "Aashvi Trivedi's Website"
  navbar:
    left:
      - href: index.qmd
        text: About
      - resume.qmd
      - href: projects.qmd
        text: Projects
        

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



